### ISSUE TITLE
TypeError: Cannot read property 'left' of undefined when element is called "row"

### ISSUE THREAD

**Issue by tsnobip** [nanohop/sketch-to-react-native#22]
I encountered this error when trying to convert an SVG to react native : 
TypeError: Cannot read property 'left' of undefined
    at determineAlignJustify (/Users/paul/sketch-to-react-native/build/attributes.js:160:36)
    at /Users/paul/sketch-to-react-native/build/flex.js:286:26
    at Array.forEach (<anonymous>)
    at flattenBoxComps (/Users/paul/sketch-to-react-native/build/flex.js:281:13)
    at /Users/paul/sketch-to-react-native/build/flex.js:291:11
    at Array.forEach (<anonymous>)
    at flattenBoxComps (/Users/paul/sketch-to-react-native/build/flex.js:281:13)
    at flattenBoxComps (/Users/paul/sketch-to-react-native/build/flex.js:276:9)
    at flattenBoxComps (/Users/paul/sketch-to-react-native/build/flex.js:260:9)
    at flattenBoxComps (/Users/paul/sketch-to-react-native/build/flex.js:260:9)

I tried removing some elements of my SVG and I then noticed that the error was happening when filtering elements called "row", folders in my case. When I renamed them, everything worked fine.

**Comment by chrisachard** [comment]
Thanks, that's great information.  I'll take a look. Are you able to share the sketch file you used (either here, or privately: chris@nanohop.com)  If not, I think we were seeing this issue on another file, so I can try to replicate it there.

**Comment by tsnobip** [comment]
Sure, you'll find it attached. It comes from the list example coming with the Material Design Stickersheet when creating a New File from Template -> Material Design.

[list.svg.zip](https://github.com/nanohop/sketch-to-react-native/files/1454511/list.svg.zip)

**Comment by chrisachard** [comment]
Great, thanks!

**Comment by agungsb** [comment]
Any update for this issue?
