### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by maximebodereau** [nanohop/sketch-to-react-native#3]
node convert.js input-file.svg 
/Users/maxime/Documents/Projects/Sktech to Html/sketch-to-react-native/convert.js:45
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by cobyhausrath** [comment]
Which version of node are you running?

**Comment by maximebodereau** [comment]
$ node -v
v6.11.4

**Comment by cobyhausrath** [comment]
Ah, that's probably it.  Give Node 8.5+ a try if you can.
```
$ node -v
v8.6.0
$ node convert.js input-file.svg
OUTPUT_FILE input-file.js
gathering elements...
...
```

**Comment by sibelius** [comment]
follow this https://github.com/nanohop/sketch-to-react-native#prerequisites

node 8 is required

**Comment by chrisachard** [comment]
Closing this issue, but I will add to the feature list to have a better error message if the node version is < 8.5
