### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by alex2wong** [nanohop/sketch-to-react-native#30]
Hi , when I run this in Ubuntu16.x  non-root mode.. Error happens..
```
>> sketch-to-react-native examples/Log\ In\ Page.svg 
gathering elements...
filtering elements...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)

```
Do you have any idea where the error come ? It is too implicit..
Actually, many png have generated in dir /components .. where it the problem??

Thanks

**Comment by M1chaelTran** [comment]
got the same error
