### ISSUE TITLE
 TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by nojas01** [nanohop/sketch-to-react-native#32]
I'm getting the following error on Ubuntu 17.10. Might be Ubuntu or my setup related but maybe someone know a fix. thanks.
```

sketch-to-react-native ~myFile.svg
/sketch-to-react-native/build/input.js:12
  var oldDefs = data.match(/\<defs\>[\s\S]*\<\/defs\>/g);
                    ^

TypeError: Cannot read property 'match' of undefined
    at prepData (/sketch-to-react-native/build/input.js:12:21)
    at ReadFileContext.callback (/sketch-to-react-native/build/index.js:89:31)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:421:13)

```

**Comment by Culzean** [comment]
I am also seeing this issue, running on windows.

**Comment by Culzean** [comment]
I'm using phyton 3.5.2
tensorflow 1.5.0
react-native-cli: 2.0.1
Node v8.9.4

so one or more of these could be causing an issue..

**Comment by vcompanyb** [comment]
Same problem here

**Comment by zjuwjf** [comment]
The same to me.

Node v9.5.0

**Comment by bkcan** [comment]
Same here

Python: 3.6
Node: v8.7.0

**Comment by alepdb** [comment]
Anyone fix this? Same problem here...

**Comment by will-r-wang** [comment]
Hey I recently ran into this issue myself. Seems like in this following line of code: sketch-to-react-native ~/Desktop/myfile.svg
/Desktop/myfile.svg should be replaced with the appropriate .svg file location when downloaded from sketch.
Hope this helps! :)
