### ISSUE TITLE
TypeError: Cannot read property 'right' of undefined

### ISSUE THREAD

**Issue by thijssmudde** [nanohop/sketch-to-react-native#33]
Latest version on Mac OS High Sierra

TypeError: Cannot read property 'right' of undefined
    at determineAlignJustify (/Users/thijssmudde/Projects/sketch-to-react-native/build/attributes.js:133:87)
    at /Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:286:26
    at Array.forEach (<anonymous>)
    at flattenBoxComps (/Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:281:13)
    at /Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:291:11
    at Array.forEach (<anonymous>)
    at flattenBoxComps (/Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:281:13)
    at flattenBoxComps (/Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:276:9)
    at flattenBoxComps (/Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:260:9)
    at flattenBoxComponents (/Users/thijssmudde/Projects/sketch-to-react-native/build/flex.js:298:3)

**Comment by setkyar** [comment]
Same issue here 😁
