### ISSUE TITLE
Cannot read property 'right' of undefined

### ISSUE THREAD

**Issue by inturbidus** [nanohop/sketch-to-react-native#37]
$> sketch-to-react-native TEMP.svg
gathering elements...
filtering elements...
TypeError: Cannot read property 'right' of undefined
    at determineAlignJustify (/Users/matthudson/Development/sketch-to-react-native/build/attributes.js:133:86)
    at /Users/matthudson/Development/sketch-to-react-native/build/flex.js:286:26
    at Array.forEach (<anonymous>)
    at flattenBoxComps (/Users/matthudson/Development/sketch-to-react-native/build/flex.js:281:13)
    at flattenBoxComps (/Users/matthudson/Development/sketch-to-react-native/build/flex.js:276:9)
    at flattenBoxComponents (/Users/matthudson/Development/sketch-to-react-native/build/flex.js:298:3)
    at _callee$ (/Users/matthudson/Development/sketch-to-react-native/build/index.js:147:36)
    at tryCatch (/Users/matthudson/Development/sketch-to-react-native/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/matthudson/Development/sketch-to-react-native/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/matthudson/Development/sketch-to-react-native/node_modules/regenerator-runtime/runtime.js:117:21)

**Comment by inturbidus** [comment]
Where can I send the SVG?

**Comment by chrisachard** [comment]
@inturbidus You can email it to me at chris@nanohop.com and I can check it out.  This is a known issue though that we're working on, so a future version should fix the issue

**Comment by muazhari** [comment]
same here
https://pastebin.com/Nfxm5Pbv
https://pastebin.com/Qj62FhX3

**Comment by muazhari** [comment]
I have a temporary tricks recommendation until next fixes are come up, how about you provide all SVG template that could be converted? using your example works on me.
